export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const LOAD_PROJECTS = 'LOAD_PROJECTS';
export const LOAD_TASKS = 'LOAD_TASKS';

export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const ADD_PROJECT_SECTION = 'ADD_PROJECT_SECTION';
export const UPDATE_PROJECT_SECTION = 'UPDATE_PROJECT_SECTION';
export const DELETE_PROJECT_SECTION = 'DELETE_PROJECT_SECTION';

export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';

export const ADD_SUBTASK = 'ADD_SUBTASK';
export const UPDATE_SUBTASK = 'UPDATE_SUBTASK';
export const DELETE_SUBTASK = 'DELETE_SUBTASK';

export const OPEN_PROJECT_EDITOR = 'OPEN_PROJECT_EDITOR';
export const CLOSE_PROJECT_EDITOR = 'CLOSE_PROJECT_EDITOR';
